# Generated by Django 4.1.5 on 2023-01-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mat_and_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material', models.TextField()),
                ('Quantity', models.IntegerField()),
                ('Mat_and_cont_Key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mat_and_content',
            constraint=models.CheckConstraint(check=models.Q(('Quantity__gte', 0)), name='non_negative'),
        ),
    ]
