# Generated by Django 4.1.5 on 2023-01-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mat_and_content_mat_and_content_non_negative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='Primary_key',
        ),
    ]
